name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name == 'push' }} # Only push on push events to main
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/upnp-client:latest # Replace with your desired image name
        # You can add more tags here, for example, based on git commit SHA
        # tags: |
        #   ${{ secrets.DOCKERHUB_USERNAME }}/upnp-client:latest
        #   ${{ secrets.DOCKERHUB_USERNAME }}/upnp-client:${{ github.sha }}
